// 動作庫 — 肌群 / 器材分類
// muscle: 胸 | 背 | 肩 | 二頭 | 三頭 | 股四頭 | 腿後側 | 臀 | 小腿 | 核心
// equipment: 槓鈴 | 啞鈴 | 機械 | 纜繩 | 自重 | 壺鈴

export const MUSCLES = ['胸', '背', '肩', '二頭', '三頭', '股四頭', '腿後側', '臀', '小腿', '核心', '全身'];

export const EXERCISES = [
  // 胸
  { id: 'bench', zh: '槓鈴臥推', en: 'Barbell Bench Press', muscle: '胸', equipment: '槓鈴' },
  { id: 'dbench', zh: '啞鈴臥推', en: 'Dumbbell Bench Press', muscle: '胸', equipment: '啞鈴' },
  { id: 'ibench', zh: '上斜槓鈴臥推', en: 'Incline Barbell Press', muscle: '胸', equipment: '槓鈴' },
  { id: 'idbench', zh: '上斜啞鈴臥推', en: 'Incline DB Press', muscle: '胸', equipment: '啞鈴' },
  { id: 'decline', zh: '下斜臥推', en: 'Decline Bench Press', muscle: '胸', equipment: '槓鈴' },
  { id: 'pecdeck', zh: '蝴蝶機夾胸', en: 'Pec Deck Fly', muscle: '胸', equipment: '機械' },
  { id: 'cablefly', zh: '纜繩飛鳥', en: 'Cable Fly', muscle: '胸', equipment: '纜繩' },
  { id: 'pushup', zh: '伏地挺身', en: 'Push-up', muscle: '胸', equipment: '自重' },
  { id: 'dips', zh: '雙槓撐體', en: 'Chest Dips', muscle: '胸', equipment: '自重' },
  // 背
  { id: 'deadlift', zh: '硬舉', en: 'Deadlift', muscle: '背', equipment: '槓鈴' },
  { id: 'pullup', zh: '引體向上', en: 'Pull-up', muscle: '背', equipment: '自重' },
  { id: 'latpull', zh: '高位下拉', en: 'Lat Pulldown', muscle: '背', equipment: '機械' },
  { id: 'bbrow', zh: '槓鈴划船', en: 'Barbell Row', muscle: '背', equipment: '槓鈴' },
  { id: 'dbrow', zh: '啞鈴划船', en: 'Dumbbell Row', muscle: '背', equipment: '啞鈴' },
  { id: 'searow', zh: '坐姿滑輪划船', en: 'Seated Cable Row', muscle: '背', equipment: '機械' },
  { id: 'pulldown', zh: '直臂下壓', en: 'Straight-arm Pulldown', muscle: '背', equipment: '纜繩' },
  { id: 'onearmrow', zh: '單臂纜繩划船', en: 'One-arm Cable Row', muscle: '背', equipment: '纜繩' },
  { id: 'backext', zh: '背伸', en: 'Back Extension', muscle: '背', equipment: '自重' },
  // 肩
  { id: 'ohp', zh: '站姿槓鈴肩推', en: 'Overhead Press', muscle: '肩', equipment: '槓鈴' },
  { id: 'dbohp', zh: '坐姿啞鈴肩推', en: 'Seated DB Shoulder Press', muscle: '肩', equipment: '啞鈴' },
  { id: 'arnold', zh: '阿諾德推舉', en: 'Arnold Press', muscle: '肩', equipment: '啞鈴' },
  { id: 'laterals', zh: '啞鈴側平舉', en: 'Lateral Raise', muscle: '肩', equipment: '啞鈴' },
  { id: 'reardelt', zh: '反向飛鳥', en: 'Reverse Fly', muscle: '肩', equipment: '啞鈴' },
  { id: 'facelift', zh: '面拉', en: 'Face Pull', muscle: '肩', equipment: '纜繩' },
  { id: 'frontraise', zh: '纜繩前平舉', en: 'Cable Front Raise', muscle: '肩', equipment: '纜繩' },
  { id: 'uprightrow', zh: '槓鈴直立划船', en: 'Upright Row', muscle: '肩', equipment: '槓鈴' },
  // 二頭
  { id: 'bbcurl', zh: '槓鈴彎舉', en: 'Barbell Curl', muscle: '二頭', equipment: '槓鈴' },
  { id: 'dbcurl', zh: '啞鈴彎舉', en: 'Dumbbell Curl', muscle: '二頭', equipment: '啞鈴' },
  { id: 'hammer', zh: '錘式彎舉', en: 'Hammer Curl', muscle: '二頭', equipment: '啞鈴' },
  { id: 'preacher', zh: '牧師椅彎舉', en: 'Preacher Curl', muscle: '二頭', equipment: '機械' },
  { id: 'cablecurl', zh: '纜繩彎舉', en: 'Cable Curl', muscle: '二頭', equipment: '纜繩' },
  { id: 'conccurl', zh: '集中彎舉', en: 'Concentration Curl', muscle: '二頭', equipment: '啞鈴' },
  // 三頭
  { id: 'pushdown', zh: '纜繩下壓', en: 'Triceps Pushdown', muscle: '三頭', equipment: '纜繩' },
  { id: 'ropedown', zh: '繩索下壓', en: 'Rope Pushdown', muscle: '三頭', equipment: '纜繩' },
  { id: 'skull', zh: '仰臥臂屈伸', en: 'Skull Crusher', muscle: '三頭', equipment: '槓鈴' },
  { id: 'closebench', zh: '窄距臥推', en: 'Close-grip Bench Press', muscle: '三頭', equipment: '槓鈴' },
  { id: 'ohdbext', zh: '啞鈴過頭臂屈伸', en: 'Overhead DB Extension', muscle: '三頭', equipment: '啞鈴' },
  { id: 'tricepsdips', zh: '雙槓撐體(三頭)', en: 'Triceps Dips', muscle: '三頭', equipment: '自重' },
  // 股四頭
  { id: 'squat', zh: '槓鈴深蹲', en: 'Barbell Back Squat', muscle: '股四頭', equipment: '槓鈴' },
  { id: 'frontsquat', zh: '前蹲', en: 'Front Squat', muscle: '股四頭', equipment: '槓鈴' },
  { id: 'legpress', zh: '腿舉', en: 'Leg Press', muscle: '股四頭', equipment: '機械' },
  { id: 'legext', zh: '腿伸機', en: 'Leg Extension', muscle: '股四頭', equipment: '機械' },
  { id: 'goblet', zh: '高腳杯深蹲', en: 'Goblet Squat', muscle: '股四頭', equipment: '啞鈴' },
  { id: 'hacksquat', zh: '哈克深蹲', en: 'Hack Squat', muscle: '股四頭', equipment: '機械' },
  { id: 'lunge', zh: '啞鈴弓步蹲', en: 'Dumbbell Lunge', muscle: '股四頭', equipment: '啞鈴' },
  { id: 'bulgarian', zh: '保加利亞分腿蹲', en: 'Bulgarian Split Squat', muscle: '股四頭', equipment: '啞鈴' },
  // 腿後側
  { id: 'rdl', zh: '羅馬尼亞硬舉', en: 'Romanian Deadlift', muscle: '腿後側', equipment: '槓鈴' },
  { id: 'legcurl', zh: '俯臥腿彎舉', en: 'Lying Leg Curl', muscle: '腿後側', equipment: '機械' },
  { id: 'seatedcurl', zh: '坐姿腿彎舉', en: 'Seated Leg Curl', muscle: '腿後側', equipment: '機械' },
  { id: 'sldl', zh: '直腿硬舉', en: 'Stiff-leg Deadlift', muscle: '腿後側', equipment: '槓鈴' },
  { id: 'dbromani', zh: '啞鈴單腿硬舉', en: 'Single-leg DB RDL', muscle: '腿後側', equipment: '啞鈴' },
  // 臀
  { id: 'hipthrust', zh: '臀推', en: 'Hip Thrust', muscle: '臀', equipment: '槓鈴' },
  { id: 'glutebridge', zh: '臀橋', en: 'Glute Bridge', muscle: '臀', equipment: '自重' },
  { id: 'kbellswing', zh: '壺鈴甩擺', en: 'Kettlebell Swing', muscle: '臀', equipment: '壺鈴' },
  { id: 'cablekick', zh: '纜繩後踢腿', en: 'Cable Kickback', muscle: '臀', equipment: '纜繩' },
  { id: 'abductor', zh: '髖外展機', en: 'Hip Abduction', muscle: '臀', equipment: '機械' },
  // 小腿
  { id: 'calfraise', zh: '站姿提踵', en: 'Standing Calf Raise', muscle: '小腿', equipment: '機械' },
  { id: 'seatedcalf', zh: '坐姿提踵', en: 'Seated Calf Raise', muscle: '小腿', equipment: '機械' },
  // 核心
  { id: 'crunch', zh: '捲腹', en: 'Crunch', muscle: '核心', equipment: '自重' },
  { id: 'plank', zh: '平板支撐', en: 'Plank', muscle: '核心', equipment: '自重' },
  { id: 'russiantwist', zh: '俄羅斯轉體', en: 'Russian Twist', muscle: '核心', equipment: '自重' },
  { id: 'hangingleg', zh: '懸吊舉腿', en: 'Hanging Leg Raise', muscle: '核心', equipment: '自重' },
  { id: 'legraise', zh: '仰臥抬腿', en: 'Leg Raise', muscle: '核心', equipment: '自重' },
  { id: 'sideplank', zh: '側平板', en: 'Side Plank', muscle: '核心', equipment: '自重' },
  { id: 'cablecrunch', zh: '纜繩捲腹', en: 'Cable Crunch', muscle: '核心', equipment: '纜繩' },
  // 全身
  { id: 'burpee', zh: '波比跳', en: 'Burpee', muscle: '核心', equipment: '自重' },
  { id: 'farmerwalk', zh: '農夫行走', en: 'Farmer\'s Walk', muscle: '背', equipment: '啞鈴' },
  // 胸 — 擴充
  { id: 'smithbench', zh: '史密斯臥推', en: 'Smith Machine Bench', muscle: '胸', equipment: '機械' },
  { id: 'cablecross', zh: '交叉纜繩夾胸', en: 'Cable Crossover', muscle: '胸', equipment: '纜繩' },
  { id: 'floorpress', zh: '地板臥推', en: 'Floor Press', muscle: '胸', equipment: '槓鈴' },
  { id: 'singlecablefly', zh: '單臂纜繩夾胸', en: 'Single-arm Cable Fly', muscle: '胸', equipment: '纜繩' },
  // 背 — 擴充
  { id: 'reversechin', zh: '反握引體向上', en: 'Chin-up', muscle: '背', equipment: '自重' },
  { id: 'australian', zh: '澳式划船', en: 'Australian Row', muscle: '背', equipment: '自重' },
  { id: 'narrowlat', zh: '窄握高位下拉', en: 'Close-grip Lat Pulldown', muscle: '背', equipment: '機械' },
  { id: 'trapdead', zh: '梯形槓硬舉', en: 'Trap Bar Deadlift', muscle: '背', equipment: '槓鈴' },
  { id: 'smithrow', zh: '史密斯划船', en: 'Smith Machine Row', muscle: '背', equipment: '機械' },
  { id: 'behindneck', zh: '頸後下拉', en: 'Behind-neck Pulldown', muscle: '背', equipment: '機械' },
  { id: 'kbellsnatch', zh: '壺鈴抓舉', en: 'Kettlebell Snatch', muscle: '背', equipment: '壺鈴' },
  // 肩 — 擴充
  { id: 'machineohp', zh: '機械肩推', en: 'Machine Shoulder Press', muscle: '肩', equipment: '機械' },
  { id: 'smithohp', zh: '史密斯肩推', en: 'Smith Machine OHP', muscle: '肩', equipment: '機械' },
  { id: 'singlelaterals', zh: '單臂側平舉', en: 'Single-arm Lateral Raise', muscle: '肩', equipment: '啞鈴' },
  { id: 'dbfront', zh: '啞鈴前平舉', en: 'DB Front Raise', muscle: '肩', equipment: '啞鈴' },
  { id: 'kbellpress', zh: '壺鈴肩推', en: 'Kettlebell Press', muscle: '肩', equipment: '壺鈴' },
  { id: 'kbellclean', zh: '壺鈴挺舉', en: 'Kettlebell Clean', muscle: '肩', equipment: '壺鈴' },
  // 二頭 — 擴充
  { id: 'reversecurl', zh: '反手彎舉', en: 'Reverse Curl', muscle: '二頭', equipment: '槓鈴' },
  { id: 'inclinecurl', zh: '上斜啞鈴彎舉', en: 'Incline DB Curl', muscle: '二頭', equipment: '啞鈴' },
  { id: 'spidercurl', zh: '蜘蛛彎舉', en: 'Spider Curl', muscle: '二頭', equipment: '啞鈴' },
  { id: 'cablehammer', zh: '纜繩錘式彎舉', en: 'Cable Hammer Curl', muscle: '二頭', equipment: '纜繩' },
  { id: 'zottman', zh: '佐特曼彎舉', en: 'Zottman Curl', muscle: '二頭', equipment: '啞鈴' },
  // 三頭 — 擴充
  { id: 'singlepushdown', zh: '單臂下壓', en: 'Single-arm Pushdown', muscle: '三頭', equipment: '纜繩' },
  { id: 'reversepushdown', zh: '反手下壓', en: 'Reverse-grip Pushdown', muscle: '三頭', equipment: '纜繩' },
  { id: 'narrowpushup', zh: '窄距伏地挺身', en: 'Diamond Push-up', muscle: '三頭', equipment: '自重' },
  { id: 'machinepushdown', zh: '機械下壓', en: 'Machine Triceps Extension', muscle: '三頭', equipment: '機械' },
  // 股四頭 — 擴充
  { id: 'boxsquat', zh: '箱式深蹲', en: 'Box Squat', muscle: '股四頭', equipment: '槓鈴' },
  { id: 'smithsquat', zh: '史密斯深蹲', en: 'Smith Machine Squat', muscle: '股四頭', equipment: '機械' },
  { id: 'singlelegpress', zh: '單腿腿舉', en: 'Single-leg Leg Press', muscle: '股四頭', equipment: '機械' },
  { id: 'stepup', zh: '登階', en: 'Step-up', muscle: '股四頭', equipment: '啞鈴' },
  { id: 'jumpsquat', zh: '深蹲跳', en: 'Jump Squat', muscle: '股四頭', equipment: '自重' },
  { id: 'boxjump', zh: '跳箱', en: 'Box Jump', muscle: '股四頭', equipment: '自重' },
  // 腿後側 — 擴充
  { id: 'nordic', zh: '北歐彎舉', en: 'Nordic Curl', muscle: '腿後側', equipment: '自重' },
  { id: 'slidingcurl', zh: '滑腿彎舉', en: 'Sliding Leg Curl', muscle: '腿後側', equipment: '自重' },
  { id: 'singlelegcurl', zh: '單腿腿彎舉', en: 'Single-leg Leg Curl', muscle: '腿後側', equipment: '機械' },
  { id: 'goodmorning', zh: '早安體前屈', en: 'Good Morning', muscle: '腿後側', equipment: '槓鈴' },
  // 臀 — 擴充
  { id: 'singlehipthrust', zh: '單腿臀推', en: 'Single-leg Hip Thrust', muscle: '臀', equipment: '啞鈴' },
  { id: 'donkeykick', zh: '驢踢腿', en: 'Donkey Kick', muscle: '臀', equipment: '自重' },
  { id: 'clam', zh: '蚌殼式', en: 'Clamshell', muscle: '臀', equipment: '自重' },
  // 小腿 — 擴充
  { id: 'singlecalf', zh: '單腿提踵', en: 'Single-leg Calf Raise', muscle: '小腿', equipment: '啞鈴' },
  { id: 'donkeycalf', zh: '驢式提踵', en: 'Donkey Calf Raise', muscle: '小腿', equipment: '機械' },
  // 核心 — 擴充
  { id: 'abwheel', zh: '腹輪', en: 'Ab Wheel Rollout', muscle: '核心', equipment: '自重' },
  { id: 'deadbug', zh: '死蟲式', en: 'Dead Bug', muscle: '核心', equipment: '自重' },
  { id: 'mountain', zh: '登山者', en: 'Mountain Climber', muscle: '核心', equipment: '自重' },
  { id: 'dragonflag', zh: '龍旗', en: 'Dragon Flag', muscle: '核心', equipment: '自重' },
  // 全身 — 擴充
  { id: 'battleropes', zh: '戰繩', en: 'Battle Ropes', muscle: '全身', equipment: '自重' },
  { id: 'sledpush', zh: '雪橇推', en: 'Sled Push', muscle: '全身', equipment: '機械' },
  // 第三批 — 更多變體
  { id: 'smithincline', zh: '上斜史密斯臥推', en: 'Smith Incline Press', muscle: '胸', equipment: '機械' },
  { id: 'declinebench', zh: '下斜啞鈴臥推', en: 'Decline DB Press', muscle: '胸', equipment: '啞鈴' },
  { id: 'widepushup', zh: '寬距伏地挺身', en: 'Wide Push-up', muscle: '胸', equipment: '自重' },
  { id: 'bandfly', zh: '彈力帶夾胸', en: 'Band Fly', muscle: '胸', equipment: '彈力帶' },
  { id: 'tbarrow', zh: 'T 槓划船', en: 'T-Bar Row', muscle: '背', equipment: '槓鈴' },
  { id: 'mechrow', zh: '機械划船', en: 'Machine Row', muscle: '背', equipment: '機械' },
  { id: 'reverseRow', zh: '反握划船', en: 'Reverse-grip Row', muscle: '背', equipment: '槓鈴' },
  { id: 'straightarmfly', zh: '直臂飛鳥', en: 'Straight-arm Fly', muscle: '背', equipment: '啞鈴' },
  { id: 'towelchin', zh: '毛巾引體', en: 'Towel Pull-up', muscle: '背', equipment: '自重' },
  { id: 'dbshrug', zh: '啞鈴聳肩', en: 'DB Shrug', muscle: '肩', equipment: '啞鈴' },
  { id: 'bbshrug', zh: '槓鈴聳肩', en: 'Barbell Shrug', muscle: '肩', equipment: '槓鈴' },
  { id: 'machinelateral', zh: '機械側平舉', en: 'Machine Lateral Raise', muscle: '肩', equipment: '機械' },
  { id: 'cablelateral', zh: '纜繩側平舉', en: 'Cable Lateral Raise', muscle: '肩', equipment: '纜繩' },
  { id: 'pike', zh: '派克伏地挺身', en: 'Pike Push-up', muscle: '肩', equipment: '自重' },
  { id: 'handstand', zh: '靠牆倒立撐', en: 'Wall Handstand Push-up', muscle: '肩', equipment: '自重' },
  { id: 'inclinebbcurl', zh: '斜板槓鈴彎舉', en: 'Incline Barbell Curl', muscle: '二頭', equipment: '槓鈴' },
  { id: 'machinecurl', zh: '機械彎舉', en: 'Machine Curl', muscle: '二頭', equipment: '機械' },
  { id: 'kbellcurl', zh: '壺鈴彎舉', en: 'Kettlebell Curl', muscle: '二頭', equipment: '壺鈴' },
  { id: 'dbskull', zh: '啞鈴碎顱', en: 'DB Skull Crusher', muscle: '三頭', equipment: '啞鈴' },
  { id: 'benchdips', zh: '凳上反撐', en: 'Bench Dips', muscle: '三頭', equipment: '自重' },
  { id: 'bandpushdown', zh: '彈力帶下壓', en: 'Band Pushdown', muscle: '三頭', equipment: '彈力帶' },
  { id: 'machineext', zh: '機械三頭伸', en: 'Machine Triceps Extension', muscle: '三頭', equipment: '機械' },
  { id: 'zercher', zh: '澤奇深蹲', en: 'Zercher Squat', muscle: '股四頭', equipment: '槓鈴' },
  { id: 'pistol', zh: '手槍深蹲', en: 'Pistol Squat', muscle: '股四頭', equipment: '自重' },
  { id: 'smithlunge', zh: '史密斯弓步', en: 'Smith Lunge', muscle: '股四頭', equipment: '機械' },
  { id: 'bandsquat', zh: '彈力帶深蹲', en: 'Band Squat', muscle: '股四頭', equipment: '彈力帶' },
  { id: 'sumodead', zh: '相撲硬舉', en: 'Sumo Deadlift', muscle: '腿後側', equipment: '槓鈴' },
  { id: 'swisscurl', zh: '瑞士球腿彎舉', en: 'Swiss Ball Leg Curl', muscle: '腿後側', equipment: '自重' },
  { id: 'bandcurl', zh: '彈力帶腿彎舉', en: 'Band Leg Curl', muscle: '腿後側', equipment: '彈力帶' },
  { id: 'smiththrust', zh: '史密斯臀推', en: 'Smith Hip Thrust', muscle: '臀', equipment: '機械' },
  { id: 'bandbridge', zh: '彈力帶臀橋', en: 'Band Glute Bridge', muscle: '臀', equipment: '彈力帶' },
  { id: 'kbsumodead', zh: '壺鈴相撲硬舉', en: 'KB Sumo Deadlift', muscle: '臀', equipment: '壺鈴' },
  { id: 'legpresscalf', zh: '腿舉提踵', en: 'Leg Press Calf Raise', muscle: '小腿', equipment: '機械' },
  { id: 'bandcalf', zh: '彈力帶提踵', en: 'Band Calf Raise', muscle: '小腿', equipment: '彈力帶' },
  { id: 'medball', zh: '藥球砸地', en: 'Medicine Ball Slam', muscle: '核心', equipment: '自重' },
  { id: 'woodchop', zh: '伐木式', en: 'Cable Wood Chop', muscle: '核心', equipment: '纜繩' },
  { id: 'birddog', zh: '鳥狗式', en: 'Bird Dog', muscle: '核心', equipment: '自重' },
  { id: 'plankknee', zh: '平板提膝', en: 'Plank Knee Tuck', muscle: '核心', equipment: '自重' },
  { id: 'sidecrunch', zh: '側捲腹', en: 'Side Crunch', muscle: '核心', equipment: '自重' },
  { id: 'medballsquat', zh: '藥球深蹲投擲', en: 'Med Ball Squat Throw', muscle: '全身', equipment: '自重' },
  { id: 'ropejump', zh: '跳繩', en: 'Jump Rope', muscle: '全身', equipment: '自重' },
  { id: 'rower', zh: '划船機', en: 'Rowing Machine', muscle: '全身', equipment: '有氧' },
  { id: 'bike', zh: '動感單車', en: 'Stationary Bike', muscle: '全身', equipment: '有氧' },
  { id: 'treadmill', zh: '跑步機', en: 'Treadmill', muscle: '全身', equipment: '有氧' },
  // 第四批 — 2026 RESEARCH 動作 (ACSM 2026 trends / Hyrox / 功能訓練 / Zone2)
  { id: 'thrusters', zh: '槓鈴挺舉蹲', en: 'Barbell Thrusters', muscle: '全身', equipment: '槓鈴' },
  { id: 'dbthrusters', zh: '啞鈴挺舉蹲', en: 'DB Thrusters', muscle: '全身', equipment: '啞鈴' },
  { id: 'wallball', zh: '藥球過頭投擲', en: 'Wall Ball', muscle: '全身', equipment: '自重' },
  { id: 'sandbagcarry', zh: '沙包肩扛', en: 'Sandbag Carry', muscle: '全身', equipment: '自重' },
  { id: 'sledpull', zh: '雪橇拉', en: 'Sled Pull', muscle: '全身', equipment: '機械' },
  { id: 'skierg', zh: '滑雪機', en: 'Ski Erg', muscle: '全身', equipment: '有氧' },
  { id: 'burpeebroad', zh: '波比跳遠', en: 'Burpee Broad Jump', muscle: '全身', equipment: '自重' },
  { id: 'assaultbike', zh: '風阻單車', en: 'Assault Bike', muscle: '全身', equipment: '有氧' },
  { id: 'turkishgetup', zh: '土耳其起身', en: 'Turkish Get-up', muscle: '全身', equipment: '壺鈴' },
  { id: 'rucking', zh: '負重行軍', en: 'Rucking', muscle: '全身', equipment: '自重' },
  { id: 'elliptical', zh: '橢圓機', en: 'Elliptical', muscle: '全身', equipment: '有氧' },
  { id: 'stairclimber', zh: '樓梯機', en: 'Stair Climber', muscle: '全身', equipment: '有氧' },
  { id: 'inclinewalk', zh: '斜走跑步機', en: 'Incline Walk', muscle: '全身', equipment: '有氧' },
  { id: 'swim', zh: '游泳', en: 'Swimming', muscle: '全身', equipment: '有氧' },
  { id: 'pallof', zh: '帕洛夫推', en: 'Pallof Press', muscle: '核心', equipment: '纜繩' },
  { id: 'bearcrawl', zh: '熊爬', en: 'Bear Crawl', muscle: '核心', equipment: '自重' },
  { id: 'deadhang', zh: '懸吊', en: 'Dead Hang', muscle: '背', equipment: '自重' },
  { id: 'cossack', zh: '哥薩克深蹲', en: 'Cossack Squat', muscle: '股四頭', equipment: '自重' },
  { id: 'bandedwalk', zh: '彈力帶側走', en: 'Banded Walk', muscle: '臀', equipment: '彈力帶' },
  { id: 'reversehyper', zh: '反向腿舉', en: 'Reverse Hyper', muscle: '腿後側', equipment: '自重' },
  { id: 'bandpullapart', zh: '彈力帶拉開', en: 'Band Pull Apart', muscle: '肩', equipment: '彈力帶' },
  { id: 'deficitdead', zh: '墊高硬舉', en: 'Deficit Deadlift', muscle: '腿後側', equipment: '槓鈴' },
  { id: 'pausesquat', zh: '暫停深蹲', en: 'Pause Squat', muscle: '股四頭', equipment: '槓鈴' },
  { id: 'jefferson', zh: '傑佛遜彎舉', en: 'Jefferson Curl', muscle: '腿後側', equipment: '槓鈴' },
];

export const EQUIPMENTS = ['槓鈴', '啞鈴', '機械', '纜繩', '自重', '壺鈴', '彈力帶', '有氧'];

export function findExercise(id) {
  return EXERCISES.find((e) => e.id === id) || null;
}

export function exerciseName(id, fallback) {
  const e = findExercise(id);
  return e ? e.zh : fallback || id;
}
